version: '3'

services:
  app:
    container_name: hemnet-scrape
    restart: always
    build: .
    env_file:
      - .env
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
